server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /positions/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
      - static_labels:
          job: docker
          project: mlops
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: .+
        target_label: job
        replacement: docker
        action: replace
      - source_labels: [__meta_docker_container_name]
        regex: .+
        target_label: project
        replacement: mlops
        action: replace
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        regex: mlops
        action: keep
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service_name
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: '/(.*)'
